package com.hp1.friendmatchingapp.enums;

public enum Hobby {
    SOCCER, BASKETBALL, PINGPONG, BADMINTON, SWIMMING, SURFING, READING, COMICS,
    MOVIE, FOOD, TRAVEL, SINGING, INSTRUMENT, ART_GALLARY, DRAWING, CRAFTING
}